#spring:
#  datasource:
#    name: test
#    url: jdbc:mysql://dev:3306/hanif
#    username: root
#    password:
#    driver-class-name: com.mysql.jdbc.Driver
#    maxActive: 20
#    initialSize: 1
#    maxWait: 10000
#    minIdle: 1
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: select 'x'
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: true
#    maxOpenPreparedStatements: 20
#
## 配置扫描 xml 文件
#mybatis:
#  mapper-locations: classpath:sqlmap/**/*.xml
#  type-aliases-package: com.hnq.study.dao.domain

#pagehelper:
#  helperDialect: mysql
#  reasonable: true
#  supportMethodsArguments: true
#  params: count=countSql