rocketmq:
  producer:
    # 发送同一类消息的设置为同一个group，保证唯一,默认不需要设置，rocketmq会使用ip@pid(pid代表jvm名字)作为唯一标示
    groupName: testGroup
    # mq的nameServer地址
    namesrvAddr: 192.168.5.243:9876
    # 如果需要同一个jvm中不同的producer往不同的mq集群发送消息，需要设置不同的instanceName
    instanceName: hanifProducer01
    # topic名称
    topic: test
    # 根据实际情况设置消息的tag
    tag: He
    # 消息最大长度 (1024 * 1024 * 6)
    maxMessageSize: 6291456
    # 发送消息超时时间
    sendMsgTimeout: 10000
