package com.hnq.study.dao.mapper;

import com.hnq.study.dao.domain.Employee;
import com.hnq.study.dao.domain.EmployeeCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface EmployeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manage_employee
     *
     * @mbggenerated
     */
    int countByExample(EmployeeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manage_employee
     *
     * @mbggenerated
     */
    int deleteByExample(EmployeeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manage_employee
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manage_employee
     *
     * @mbggenerated
     */
    int insert(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manage_employee
     *
     * @mbggenerated
     */
    int insertSelective(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manage_employee
     *
     * @mbggenerated
     */
    List<Employee> selectByExampleWithRowbounds(EmployeeCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manage_employee
     *
     * @mbggenerated
     */
    List<Employee> selectByExample(EmployeeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manage_employee
     *
     * @mbggenerated
     */
    List<Employee> selectPaginationByExample(EmployeeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manage_employee
     *
     * @mbggenerated
     */
    int insertOrUpdateBySelective(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manage_employee
     *
     * @mbggenerated
     */
    void batchInsert(List<Employee> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manage_employee
     *
     * @mbggenerated
     */
    void batchUpdateByPrimaryKey(List<Employee> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manage_employee
     *
     * @mbggenerated
     */
    void batchUpdateByPrimaryKeySelective(List<Employee> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manage_employee
     *
     * @mbggenerated
     */
    Employee selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manage_employee
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Employee record, @Param("example") EmployeeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manage_employee
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Employee record, @Param("example") EmployeeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manage_employee
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manage_employee
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Employee record);
}