server:
  port: 8082

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.5.241:3306/hanif?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: dashu0701
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  http:
    encoding:
      charset: UTF-8
      enabled: true
  ## 视图解析器 ##
  mvc:
    view:
      prefix: /pages/
      suffix: .jsp

# 配置扫描 xml 文件
mybatis:
  mapper-locations: classpath:sqlmap/**/*.xml
  type-aliases-package: com.hnq.study.dao.domain
